server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    #preferIpAddress: true通过ip来发现
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/,http://peer3:8770/eureka/